development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: .
  pool: 5
  username: .
  password: .

production:
  adapter: sqlite3
  encoding: unicode
  database: db/production.sqlite3
  pool: 5