development:
  adapter: postgresql
  encoding: unicode
  database: rcciita_d
  pool: 5
  username: kaylors
  password: dragonx

test:
  adapter: postgresql
  encoding: unicode
  database: .
  pool: 5
  username: .
  password: .

production:
  adapter: postgresql
  encoding: unicode
  database: rcciita_d
  pool: 5
  username: kaylors
  password: dragonx